* Guideline

 Homework for week 03. Due: 11h59pm on Thursday, 2022-09-22. 

 Please submit your solutions in a single PDF on Blackboard.  Multiple submissions are possible before the due time; the last submission will be graded. 


* Exercise 1 (points = 12) 

  Rewrite the statements below using quantifiers and variables. For example, a statement like "Even numbers are divisible by 2" becomes: "for each even number n, n is divisible by 2", or "for each number n, if n is an even number, then n is divisible by 2". You do not necessarily need to use the exact words or patterns as above. 

1) No two leaves are alike.
2) Even integers equals twice some integer.
3) The sum of two positive integers is a positive number.



* Exercise 2 (points = 18)

  Write a negation for each statement. For example, the negation of "for any real number x, if x * x > 4 then x > 2" becomes "there exists a real number x, x * x > 4 and x <= 2".   


1)  for any real numbers x, y, z, (x + y) + z  equals to x + (y + z). 
2)  for any integer d, if 11 / d is an integer then d = 11.
3)  for any real nunber x, if x * (x + 5) > 0 then x > 0 or x < −5.
4)  for any positive integer n, if n is prime then n is odd or n = 2.
5)  for any integers a, b and c, if a − b is even and b − c is even, then a − c is even.
6)  for any integer n, if n is divisible by 6, then n is divisible by both 2 and 3.



* Exercise 3 (points = 24)

Determine whether the statements below are true or false. You do not need to give the reasons. 

1. 119 is a prime number.

2. 161 is a prime number.

3. 42k is an even number for any integer k.

4. For each integer n with 2 <= n <= 6, n^2 − n + 11 is a prime number.

5. The average of any two odd integers is odd.

6. For any real number x, if x * x >= 4, then x >= 2.

7. For any real numbers x and y, x^2 - 2xy + y^2 >= 0. 

8. There exists an integer x, such that (2x + 1)^2 is even.

 
* Exercise 4 (points = 14)

- Prove the following statement: There exist two integers m and n such that m > 1, n > 1 and 1/m + 1/n is an integer.
- Prove the following statement: There is an integer n such that 2n^2 - 5n + 2 is prime.

  [Hint: to prove an existential proposition with direct proof, you can simply find the element that makes the predicate be true.)


* Exercise 5 (points = 14) 

- Prove the following proposition: An even number multiplied by an integer is an even number. 
- Prove the following proposition: An odd number multiplied by an odd number is an odd number.   



* Exercise 6 (points = 18)

Below are two definitions of odd numbers.

- Definition 1. An integer n is an odd number if n = 2k+1 for some integer k.

- Definition 2. An integer n is an odd number if n = 2k-1 for some integer k.  
  
Prove the two definitions are equivalent following the two steps below. 

1. First, prove any odd number n defined in the sense of Definition 1 is also an odd number defined in the sense of Definition 2.

2. Second, prove any odd number n defined in the sense of Definition 2 is also an odd number defined in the sense of Definition 1.

  

