* Guideline

 Homework for week 01. Due: 11h59pm on Thursday, 2022-09-08. 

 Please submit your solutions in a single PDF on Blackboard. Please do not include your name or email address in your homework.

 Multiple submissions are possible before the due time; the last submission will be graded. 


* Exercise 1 (score = 10)
Construct the truth table for the following statement forms:

1. false \/ p 
2. True /\ p

   
* Exercise 2 (score = 30)

Write truth tables for the following statement  forms.

1. p -> q
2. ~p \/ q
3. q -> p
4. ~q \/ p
5. ~q -> ~p
6. ~p -> ~q             

* Exercise 3   (score = 15)
   
Among the six statement forms in Exercise 2, find at least five pairs that are equivalent? For example, if you believe statement forms 1 and 2 in Exercise 2 are equivalent, you have found a pair (1, 2). 

* Exercise 4. (score = 20)

Make a truth table for the prroposition ~P ∧ (Q → P). What can you conclude about P and Q if you know the statement is true?



* Exercise 5. (score = 15)
For each  statement form below, use truth tables to determine  if it is a tautology, contradiction, or neither. 


1. (∼p\/q)\/(p/\∼q)
2. (p/\∼q)∧(∼p\/q)
3. (p/\q)\/(∼p\/(p/\∼q))  




* Exercise 6. (score = 10)

  Check if the two statement forms below are logically equivalent using a truth table

-  p \/ q -> r
- (p -> r) /\ (q ->r)

